In [1]:
import numpy as np
from scipy import sparse

# create an identity matrix of size 4x4
identity_matrix = np.eye(4)
print("NumPy array:\n{}".format(identity_matrix))

# convert matrix to sparse matrix to save memory
sparse_matrix = sparse.csr_matrix(identity_matrix)
print("SciPy sparse CSR matrix:\n{}".format(sparse_matrix))

# construct sparse matrix from scratch since often dense representations don't fit in memory
vector = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)

identity_matrix_coo_format = sparse.coo_matrix((vector, (row_indices, col_indices)))
print("COO representation:\n{}".format(identity_matrix_coo_format))


NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
